### ISSUE TITLE
When running cron:run manually result is not set

### ISSUE THREAD

**Issue by rat4m3n** [predakanga/CronBundle#12]
> [Doctrine\DBAL\DBALException]
>   An exception occurred while executing 'INSERT INTO CronJobResult (runAt, runTime, result, output, job_id) VALUES (?, ?, ?, ?, ?)' with params {"1":"201
>   3-04-10 17:22:42","2":0.055889844894409,"3":null,"4":"Done and updated 11 profiles.\n","5":1}:

  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'result' cannot be null

Shall we allow null for this column?

**Comment by cordoval** [comment]
no, there is always a result you just set it and avoid the problem

**Comment by rat4m3n** [comment]
Hmm.. How / where do I need to set it? In my command somewhere?

**Comment by rat4m3n** [comment]
@cordoval Could anyone help me with this one please? Nothing has been mentioned about 'result' in docs and without this I am getting an error on each interval.

**Comment by gurgenhakobyan** [comment]
have the same issue. how to set that result?

**Comment by rat4m3n** [comment]
```
/**
 * @param InputInterface  $input
 * @param OutputInterface $output
 *
 * @return int
 */
protected function execute(InputInterface $input, OutputInterface $output)
{
    // do stuff...

    return CronJobResult::SUCCEEDED;
}
```

**Comment by gurgenhakobyan** [comment]
Thanks, I think should be added in documentation.
