### ISSUE TITLE
colourstream/cron-bundle dev-master requires symfony/symfony 2.1.* -> no matching package found

### ISSUE THREAD

**Issue by ghodkekrishna** [predakanga/CronBundle#19]
Hi ,
   I am using this bundle with Symfony 2.5.4 it`s giving me error of

Problem 1
    - Installation request for colourstream/cron-bundle dev-master -> satisfiable by colourstream/cron-bundle[dev-master].
    - colourstream/cron-bundle dev-master requires symfony/symfony 2.1.\* -> no matching package found.

**Comment by Witoldinio** [comment]
Did you found answer for this question?
Did you solved this issue somehow?
