### ISSUE TITLE
Changing interval throws exception

### ISSUE THREAD

**Issue by rickard2** [predakanga/CronBundle#2]
When changing the interval of a Command, an exception is thrown: 

```
  [BadMethodCallException]                                                                        
  Unknown property 'interval' on annotation 'ColourStream\Bundle\CronBundle\Annotation\CronJob'.  
```

How to reproduce: 
1. Create command with (at)CronJob annotation 
2. run cron:scan
3. Change interval
4. run cron:scan

**Comment by predakanga** [comment]
Thanks for the report - this was due to the hasty refactoring of the annotations before release, to make things a bit more user friendly. Should be fixed up nicely now.
